"""PARASOL paper — table-data I/O helper (the ``figures/_figdata.py`` analogue).

Two jobs, mirroring the figure tier:
  * RENDERERS call :func:`load` to read ``tabdata/<stem>.json`` and emit the LaTeX
    ``tabular`` body.  That is all a renderer ever touches — no solver, no jax.
  * DATA SCRIPTS call :func:`dump` to write the recomputed numbers to that json.

Also carries the number formatting, so every table typesets values the same way and
paper.tex never holds a hand-transcribed digit.
"""
from __future__ import annotations

import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
TABDATA = os.path.join(HERE, "tabdata")

AXIS_TEX = {
    "b": r"$b$",
    "q": r"$q$",
    "chi_A": r"$\chi_A$",
    "chi_B": r"$\chi_B$",
    "chi_Ay": r"$\chi_{Ay}$",
    "chi_By": r"$\chi_{By}$",
}


def tabdata_path(stem):
    return os.path.join(TABDATA, f"{stem}.json")


def dump(stem, obj):
    """Write the recomputed numbers for a table to tabdata/<stem>.json."""
    os.makedirs(TABDATA, exist_ok=True)
    with open(tabdata_path(stem), "w") as f:
        json.dump(obj, f, indent=2)
    return tabdata_path(stem)


def load(stem):
    """Read tabdata/<stem>.json (the ONLY thing a renderer reads)."""
    p = tabdata_path(stem)
    if not os.path.exists(p):
        raise FileNotFoundError(
            f"missing table data: {os.path.relpath(p, HERE)}\n"
            f"  build it with:  python {stem}_data.py   "
            f"(or: python make_tabdata.py --tab {stem})")
    with open(p) as f:
        return json.load(f)


# ------------------------------------------------------------------ formatting ----------------
def sci(x, sig=2):
    """``1.857e-9`` -> ``$1.9\\times10^{-9}$`` (two significant figures by default)."""
    s = f"{float(x):.{sig - 1}e}"
    mant, exp = s.split("e")
    return rf"${mant}\times10^{{{int(exp)}}}$"


def pow10(x):
    """``1e-4`` -> ``$10^{-4}$``; falls back to :func:`sci` if not a power of ten."""
    from math import isclose, log10
    e = log10(abs(float(x)))
    if isclose(e, round(e), abs_tol=1e-12):
        return rf"$10^{{{int(round(e))}}}$"
    return sci(x)


def axis(name):
    return AXIS_TEX.get(name, name.replace("_", r"\_"))


def write_tex(stem, header, rows, *, note=None):
    """Write ``<stem>.tex``: a ``ruledtabular`` block for paper.tex to ``\\input``.

    ``header`` is a list of column headings (LaTeX); ``rows`` a list of row cell lists.
    The caption and ``\\label`` stay in paper.tex — they are author-owned prose.
    """
    ncol = len(header)
    align = "l" + "c" * (ncol - 1)
    lines = [f"% generated by {stem}_tex.py from tabdata/{stem}.json — do not edit by hand",
             r"\begin{ruledtabular}",
             rf"\begin{{tabular}}{{{align}}}",
             "  " + " & ".join(header) + r" \\",
             r"  \colrule"]
    for r in rows:
        lines.append("  " + " & ".join(r) + r" \\")
    lines += [r"\end{tabular}", r"\end{ruledtabular}"]
    if note:
        lines.insert(1, f"% {note}")
    path = os.path.join(HERE, f"{stem}.tex")
    with open(path, "w") as f:
        f.write("\n".join(lines) + "\n")
    return path
